version: "3.8"

services:
  app:
    build:
      context: .
      target: dataset-image
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "127.0.0.1:5077:5077"
    depends_on:
      - postgres
    env_file:
      - '.env'

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataset
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  alembic:
    build:
      context: .
      target: alembic-image
    env_file:
      - '.env'
    volumes:
      - ./migrations/:/dataset/migrations/
      - ./dataset/:/dataset/dataset/
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
