version: "3.8"

services:
  dataset:
    build:
      target: dataset-image
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "127.0.0.1:5081:5081"
    environment:
      - HOST=0.0.0.0
      - PORT=5081
    depends_on:
      - postgres
    env_file:
      - '.env'

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataset
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  alembic:
    build:
      target: alembic-image
    env_file:
      - '.env'
    volumes:
      - ./migrations/:/dataset/migrations/
      - ./dataset/:/dataset/dataset/
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.55.0
    ports:
      - "127.0.0.1:9091:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./metrics/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.3.0
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  postgres-data:
  prometheus-data:
  grafana-data:
